name: Deploy Resources

on:
  workflow_dispatch: # Allows you to run the workflow manually
  schedule:
    - cron: '0 22 * * 1-5' # Runs at 11 PM UTC / 9 AM AEST, Monday to Friday

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZUREKEY }}

    - name: Create resource group
      run: |
        az group create --name SecurityCopilot --location eastus
        
    - name: Deploy Bicep template
      run: |
        az deployment group create --name CopilotDeployment --resource-group SecurityCopilot --template-file ./main.bicep --parameters ./main.bicepparam
